### ISSUE TITLE
[ERROR] Possible Node version incompatibility with @happy-dom/global-registrator

### ISSUE THREAD

**Issue by angelhdzmultimedia** [piscis/nuxt-quasar-boilerplate#27]
In my computer, VSCode, Node v18.1.0, it works like a charm.

But in stackblitz.com, which has Node v16.14.2, I get this error:
![image](https://user-images.githubusercontent.com/10191085/218249792-14c32dd4-4cfb-4082-82a4-872c72c10c02.png)

I tried many things, from creating the project twice, to deleting node_modules and pnpm-lock.json and reinstalling everything, to matching packages versions, to removing some of the properties in the Nuxt Config. Error still comes.

Thank you in advance.

**Comment by piscis** [comment]
Thanks for reporting I'm checking this

**Comment by piscis** [comment]
@angelhdzmultimedia I made some changes to the engines section of package.json to allow NodeJS >=16.x it should work now looking at Stackblitz.

https://stackblitz.com/github/piscis/nuxt-quasar-boilerplate

**Comment by angelhdzmultimedia** [comment]
Wow man. Can't believe how long I've been researching and experimenting to get Quasar working on Nuxt 3.
First time looking at the running app without any errors or warnings. I'm not even gonna doubt about the hydration mistmach errors that you mentioned were gone, so I will use my time to hit that HELLO button many times until all the days and hours of frustration get relieved.

I hope Nuxt team or Quasar team adds an official module for all this.

In the meantime, I give you appreciation for your kindness, your fast responses, your time, your energy, and your solutions.



![image](https://user-images.githubusercontent.com/10191085/218280128-34da429a-39b4-4048-8968-228d1ceeb1e8.png)

![image](https://user-images.githubusercontent.com/10191085/218280563-1c01f66c-cc5c-4cbe-a6f0-b1db441f6e41.png)

**Comment by angelhdzmultimedia** [comment]
Nice touch! I've been doing this manually from the first time I started with stackblitz.com.
![image](https://user-images.githubusercontent.com/10191085/218280577-c1721f1e-ad52-4527-9a8e-717953d519c9.png)

**Comment by piscis** [comment]
Thank you for the nice feedback I'm glad I could help a little bit.
