### ISSUE TITLE
[ERROR] Quasar hooks and plugins undefined on the client

### ISSUE THREAD

**Issue by angelhdzmultimedia** [piscis/nuxt-quasar-boilerplate#31]
Sorry to bring negative news, after the success of solving the stackblitz.com issue and getting a working Nuxt 3 + Quasar application.

This time, the issue is with Quasar's hooks (like useQuasar) and plugins (like Dark).

I, as usual, went quickly to install the Dark plugin in the Vue Quasar Plugin definition.

```ts
import * as components from 'quasar'
const { Dark } = components

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(components.Quasar, {
    plugins: {
      Dark,
    },
    components,
  })
})

```

Then I got a "Dark is not defined" error on the client (browser).

![image](https://user-images.githubusercontent.com/10191085/218286283-f8110a80-4029-4bca-a512-624f903ebacd.png)

So I proceeded, obviously, and tried using the Vue's Component way, with the useQuasar hook and the dark property.
I got the same error "useQuasar is not defined".

Then I tried renaming the plugins/quasar.ts file to plugins/quasar.client.ts. Same error.

Tried setting 2 Quasar plugins, one with quasar.server.ts and the other with quasar.client.ts. Same error.

Finally, tried setting ssr: false for the index route  specifically (where I intended to use the Dark plugin).

Trying to think what's the issue because in the server side of Nuxt, all these hooks and plugins are being printed in the console
and in the Nuxt config, we are setting `build: { transpile: ['quasar'] }`, that should transpile everything in the package.

I'm using your Stackblitz project. Didn't touch anything.

Only `pnpm install && pnpm dev` in the terminal, `plugins/quasar.ts` to install the Dark plugin, and `components/HelloWorld.vue` to use the plugin.

```vue
<script setup lang="ts">
import {Dark} from 'quasar'

Dark.set(true) 
</script>
```

### Final Words
I was writing a post in a spanish Vue group on Facebook to promote this boilerplate (as experimental with the hope of an official module, to get people talking and hyped for Quasar in Nuxt), and before posting, decided to make some tests, and I'm glad I didn't send the post. Hope there's a solution for this. Only being able to use the hooks and the plugins is what's preventing me to fully embrace Nuxt + Quasar + SSR. Otherwise I would have to keep using it in SPA mode.

Again, thank you for all your efforts.

**Comment by angelhdzmultimedia** [comment]
### Update
Went a step further, and made a Server API server/api/dark/toggle with the code:

```ts
import { Dark} from 'quasar'

export default defineEventHandler((event) => {
  Dark.toggle()
})

```

And in the client:

```vue
<script setup lang="ts">
async function toggleDarkMode() {
  await useFetch(() => '/api/dark/toggle')
}
</script>

<template>
<q-btn @click="toggleDarkMode"/>
</template>
```
Nothing happens. No re-render.
And in the server api, Dark.isActive is always false.

I thought about just sending the new value for dark mode to the client, and letting the client update the dark mode,
but considering neither does Dark plugin or useQuasar hook work in the client, I wouldn't be able to do anything.

It's strange. Maybe is me doing something the wrong way!? I'm new to SSR...

**Comment by angelhdzmultimedia** [comment]
### Workaround

I defined the hooks and plugins of Quasar I wanted as auto-imports in Nuxt config, and the "x is not defined" errors went away.

`nuxt.config.ts`
```ts
imports: {
    dirs: ['stores/**'],
    imports: [
      {from: 'quasar', name: 'Dark'},
      {from: 'quasar', name: 'Notify'}
    ],
    
  },
```

`app.vue`
```vue
<script setup lang="ts">
Dark.set(true)
</script>

<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>

```

![image](https://user-images.githubusercontent.com/10191085/218299802-6f5190c2-6b97-420e-97ae-606b60e74f7c.png)


But still feels "hacky"... all package's members should be available in the client...

### And a new bug appeared
When I open the app in the browser, it first is Light Mode with the <HelloWorld/> component showing, and after 1-2 seconds,
it then turns Dark Mode, creating an annoying screen "flash" effect.

And I just realized why it works in my app where I'm using jsdom instead of @happy-dom/global-registrator: Because my Quasar Nuxt Plugin file name is quasar.client.ts and not quasar.ts.

Renaming the plugin to `quasar.client.ts` makes the Dark Mode apply instantly (because is not the server rendering the page now), but with the bad effect of getting [Vue Warn} errors about components:
![image](https://user-images.githubusercontent.com/10191085/218300071-dcc82947-a01d-4867-9690-3c9580a4c690.png)

I think I'm gonna wait until Nuxt or Quasar team make this official and keep using Quasar as SPA in the meantime.

**Comment by piscis** [comment]
Okay I'm going to look into this, maybe there is a way I could add darkmode support to the boilerplate example

**Comment by angelhdzmultimedia** [comment]
### Update 3

I managed to get rid of the "Dark is undefined" error, by using a composable!

`composables/dark.ts`
```ts
import { Dark } from 'quasar';

export const useDark = () => {
  function set(status: boolean) {
    Dark.set(status);
  }
  return { set };
};
```

`app.vue`
```vue
<script setup lang="ts">
useDark().set(true)
</script>

<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>

```

It worked right away.

But the annoying flash is still happening:


https://user-images.githubusercontent.com/10191085/218307332-77dd300a-3dce-476f-a6f4-3155837ed2a6.mp4

**Comment by angelhdzmultimedia** [comment]
### Update 4

After I was about to get insane and abandon SSR, 
I came up with an idea and seems to work.

1. Doing all the Quasar plugins stuff in a composable to prevent the "x is not defined" errors.
2. Setting the dark mode before mounting the whole view (Layout plus pages) and showing a loading animation.

![chrome_0kGSBGRDn1](https://user-images.githubusercontent.com/10191085/219611294-8bc202e4-01f6-496a-b12e-f7b20c45280b.gif)


Sad part of this is, the loading animation will not be in dark mode...
I also tried using a server/middleware to set the dark mode there... it doesn't apply the dark mode at all.

And all this is only trying to get the Dark plugin working, I haven't tried the other Quasar plugins like Notify, AppFullscreen, Dialog, etc.

**Comment by piscis** [comment]
Hi thanks for all the work! Can you provide a simple example of what you've done, maybe there is a way to incorporate this into the boilerplate. Can you provide a link to a stack blitz box?

**Comment by angelhdzmultimedia** [comment]
https://stackblitz.com/edit/nuxt-starter-q99pew

Edit: Added dark mode persisting in local storage.

**Comment by JasonLandbridge** [comment]
Great work @angelhdzmultimedia! Thanks to you I managed to resolve my `useQuasar is not defined` error.

The fix is creating an `./composables/quasar.ts` composable:

```typescript
import { useQuasar } from 'quasar'

export const useNuxtQuasar = () => {
    return useQuasar()
}
```
Then it can be used in a template like this:

```vue
<template></template>

<script setup lang="ts">
import Log from 'consola';

const $q = useNuxtQuasar()

// get status
Log.info($q.dark.isActive) // true, false
</script>
```

**Comment by JasonLandbridge** [comment]
@angelhdzmultimedia The dark-mode flikker might be related to this: https://quasar.dev/quasar-plugins/dark#note-about-ssr

**Comment by piscis** [comment]
@angelhdzmultimedia  Thanks for the update I guess the easiest way to get plugins working is by re-export the useQuasar composable.  I extended the example with dark mode support. There is a "Kinda" workaround for SSR and the flickering. 

Darkmode can be triggered by appending dark=1 as query parameter. 

Anyway since dark mode support + SSR is kinda flaky (https://quasar.dev/quasar-plugins/dark#note-about-ssr) in Quasar I would suggest to track the darkMode state with NuxtState and based on the users preference set it and force quasar to reevaluate the component tree to remove q-dark classes on its components where necessary.

Can you close the issue if that works for you?

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia Thanks for the update I guess the easiest way to get plugins working is by re-export the useQuasar composable. I extended the example with dark mode support. There is a "Kinda" workaround for SSR and the flickering.
> 
> Darkmode can be triggered by appending dark=1 as query parameter.
> 
> Anyway since dark mode support + SSR is kinda flaky (https://quasar.dev/quasar-plugins/dark#note-about-ssr) in Quasar I would suggest to track the darkMode state with NuxtState and based on the users preference set it and force quasar to reevaluate the component tree to remove q-dark classes on its components where necessary.
> 
> Can you close the issue if that works for you?

Wow this response is on fire! Thanks for being so kind, and for all the useful info you are providing.
The part were you mention `dark = 1` and 

> darkMode state with NuxtState and based on the users preference set it and force quasar to reevaluate the component tree to remove q-dark classes on its components

Sounds like the things I tried to achieve with server or client middleware, to inject the view with the dark mode already applied.
This sounds like the right direction, so yeah, I can finally close this issue.

Cheers!

**Comment by angelhdzmultimedia** [comment]
### Update 5 

Instead of making a composable to use Quasar module's members (plugins, components, etc.),
we can use the Nuxt Auto Imports.

In the Nuxt Configuration File, we can define the auto imports for quasar, that way,
we don't have to use composables, and at the same time, benefit from not having to import anything.

(I used a composable only for persisting the dark mode in local storage).

**Check it out in the experimental branch** https://github.com/angelhdzmultimedia/quasar-nuxt-bp-dark/tree/experimental

**Comment by piscis** [comment]
Why not use https://nuxt.com/docs/api/composables/use-cookie and make SSR + Client working with darkmode?

The Idea registering everything via nuxt.config is greate did you a analyze of the bundle to see if it could still be treeshaked I'm afraid it could load the complete quasar framework in the client that way

**Comment by angelhdzmultimedia** [comment]
> Why not use https://nuxt.com/docs/api/composables/use-cookie and make SSR + Client working with darkmode?
> 
> The Idea registering everything via nuxt.config is greate did you a analyze of the bundle to see if it could still be treeshaked I'm afraid it could load the complete quasar framework in the client that way

Ah! Because persisting the dark mode in local storage was something quick that I felt like doing to test, wasn't really a feature implementation.

Yeah we can use VueUse or nuxt cookie composables for that.

And about the tree shaking of quasar, I haven't checked how that works, but I do know that the auto imports are like a magic syntax sugar, the types of the imports get generated so we can use the module's stuff, but at compilling time, the imports are added. It works like the compiler macros. But tree shaking is managed by the bundlers to ensure no dead code.

**Comment by joaofranciscoguarda** [comment]
I'm working only with Vue3 and Quasar, falling in the same error, trying to use useQuasar/Dialog on my ts file for a util, but the error always comes, I read the tread but it's only a Nuxt solution, there is any other discussion about it?

![image](https://github.com/piscis/nuxt-quasar-boilerplate/assets/95258409/f7e519b6-d86c-4d1a-9721-0a8ab266c509)

![image](https://github.com/piscis/nuxt-quasar-boilerplate/assets/95258409/8a89be1a-de73-4846-890d-c1d3f47e8ec9)

If there is not support for hooks on Ts files, pls, let me know. Thanks!

**Comment by angelhdzmultimedia** [comment]
> I'm working only with Vue3 and Quasar, falling in the same error, trying to use useQuasar/Dialog on my ts file for a util, but the error always comes, I read the tread but it's only a Nuxt solution, there is any other discussion about it?
> 
> ![image](https://user-images.githubusercontent.com/95258409/247941129-f7e519b6-d86c-4d1a-9721-0a8ab266c509.png)
> 
> ![image](https://user-images.githubusercontent.com/95258409/247941313-8a89be1a-de73-4846-890d-c1d3f47e8ec9.png)
> 
> If there is not support for hooks on Ts files, pls, let me know. Thanks!

When using Quasar in external files (.js, .ts), we use the plugins instead of the `useQuasar` hook that is intended to be used inside Vue components.

```ts
import {Dark, Dialog, Notify} from 'quasar'

Notify.create({
 message: 'Success!',
 type: 'positive',
})
```
But to access `$q` in the file of the router definition, you can use it inside the route guards callbacks like `beforeEach` like this:

```ts
router.beforeEach((to, from) => {
const $q = useQuasar() 
  console.log($q.version)
})
```

And why are you using a router explicitly, when Nuxt already have VueRouter integrated?
Just add your pages inside the `pages` directory https://nuxt.com/docs/guide/directory-structure/pages,
and your route guards in the `middleware` directory! https://nuxt.com/docs/guide/directory-structure/middleware

And by the way, you may want to check the `nuxt-quasar-ui` module for Nuxt 3, officially added in the modules section. https://nuxt.com/modules/quasar

**Comment by joaofranciscoguarda** [comment]
> 

Thank for the reply! Nuxt + Quasar may be our next step.
